### ISSUE TITLE
Error when installing latest mthree

### ISSUE THREAD

**Issue by rathishcholarajan** [Qiskit-Partners/mthree#97]
`qiskit-ibm-runtime` [builds](https://github.com/Qiskit/qiskit-ibm-runtime/runs/5655075572?check_suite_focus=true#step:4:220) started failing after the latest mthree release 0.21.0.

`pip install mthree` nows throws below error:

```
(qiskit-ibm-runtime) rathish@Rathishs-MacBook-Pro qiskit-ibm-runtime % pip install -I mthree
Collecting mthree
  Using cached mthree-0.21.0.tar.gz (730 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/bin/python /Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/tmp6kxr64xk
       cwd: /private/var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/pip-install-spm6gvgs/mthree_86c865a23ace4bf7934fd7dcf00c7c40
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/pip-build-env-9osqm8ic/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/pip-build-env-9osqm8ic/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/pip-build-env-9osqm8ic/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 130, in <module>
    File "setup.py", line 114, in write_version_py
  FileNotFoundError: [Errno 2] No such file or directory: 'mthree/version.py'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2a/c0/984e28773f84c3b60a9eede448a7f1e350593f9c70c757242f8a2e5cbe2b/mthree-0.21.0.tar.gz#sha256=a0daa86b88111c03cba1070797ac8dc316a2618fa227ebc08638c767477f9b82 (from https://pypi.org/simple/mthree/). Command errored out with exit status 1: /Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/bin/python /Users/rathish/opt/anaconda3/envs/qiskit-ibm-runtime/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/jt/2qwx0rx17tl94gnll6wjftjc0000gn/T/tmp6kxr64xk Check the logs for full command output.
```

**Comment by mtreinish** [comment]
This will be fixed by: https://github.com/Qiskit-Partners/mthree/pull/96
